import { firebaseApi } from './firebase-client.js';

const shows = [
    { id: 'verao-seul', title: 'Aquele verão em Seul', genre: 'Romance', key: 'romance', country: 'Coreia do Sul', episodes: 8, year: 2024, rating: '9,1', badge: 'NOVO', image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=80', description: 'Um encontro inesperado transforma um verão comum em uma memória impossível de apagar.' },
    { id: 'vizinho-astro', title: 'Meu vizinho é um astro', genre: 'Comédia', key: 'comedia', country: 'Coreia do Sul', episodes: 10, year: 2024, rating: '8,8', badge: 'POPULAR', image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=700&q=80', description: 'Ele é famoso. Ela prefere o silêncio. O novo apartamento deles só tem uma regra: não se apaixonar.' },
    { id: 'carta-imperatriz', title: 'A carta da imperatriz', genre: 'Histórico', key: 'historico', country: 'China', episodes: 16, year: 2023, rating: '9,3', badge: 'EXCLUSIVO', image: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=700&q=80', description: 'Uma carta perdida no tempo pode mudar o destino de um reino inteiro e de dois corações.' },
    { id: 'ultimo-bilhete', title: 'O último bilhete', genre: 'Mistério', key: 'misterio', country: 'Japão', episodes: 6, year: 2024, rating: '8,9', badge: 'NOVO', image: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=700&q=80', description: 'Todos na estação escondem um segredo. Um bilhete anônimo vai revelar o mais perigoso deles.' },
    { id: 'som-cafe', title: 'O som do nosso café', genre: 'Romance', key: 'romance', country: 'Coreia do Sul', episodes: 12, year: 2023, rating: '8,7', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=700&q=80', description: 'Um café pequeno, uma playlist compartilhada e o som de duas pessoas encontrando seu ritmo.' },
    { id: 'primavera', title: 'Quando a primavera chegar', genre: 'Drama', key: 'drama', country: 'Coreia do Sul', episodes: 12, year: 2024, rating: '9,0', image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=900&q=80', description: 'Às vezes, recomeçar é só encontrar coragem para voltar ao lugar onde tudo começou.' },
    { id: 'flor-noite', title: 'A flor que floresce à noite', genre: 'Romance', key: 'romance', country: 'Coreia do Sul', episodes: 16, year: 2024, rating: '9,4', image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=700&q=80', description: 'Uma florista e um músico aprendem que os encontros mais bonitos também podem ser silenciosos.' },
    { id: 'segundo-plano', title: 'Amor em segundo plano', genre: 'Drama', key: 'drama', country: 'Japão', episodes: 8, year: 2023, rating: '8,6', image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=700&q=80', description: 'Ela sempre esteve atrás das câmeras. Até que alguém decide enxergá-la.' },
    { id: 'contrato-outono', title: 'O contrato de outono', genre: 'Comédia', key: 'comedia', country: 'China', episodes: 12, year: 2024, rating: '8,5', image: 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?auto=format&fit=crop&w=700&q=80', description: 'Um contrato de namoro parece simples, até os dois esquecerem onde termina a atuação.' }
];

const state = { list: JSON.parse(localStorage.getItem('dramaplus-list') || '[]'), user: JSON.parse(localStorage.getItem('dramaplus-user') || 'null'), query: '', filter: 'todos' };
const app = document.createElement('div');
app.id = 'app';
document.body.innerHTML = '';
document.body.appendChild(app);

const getShow = (id) => shows.find((show) => show.id === id);
const saveState = () => { localStorage.setItem('dramaplus-list', JSON.stringify(state.list)); if (firebaseApi.enabled && state.user?.uid) firebaseApi.saveList(state.user.uid, state.list).catch(() => { }); };
const go = (path) => { window.location.hash = path; };

function header() {
    const route = window.location.hash || '#/';
    return `<header class="topbar app-topbar"><a class="brand" href="#/"><span class="brand-mark">D</span><span>Drama<span class="brand-accent">Plus</span></span></a><nav class="main-nav"><a class="nav-link ${route === '#/' ? 'active' : ''}" href="#/">Início</a><a class="nav-link ${route === '#/explorar' ? 'active' : ''}" href="#/explorar">Explorar</a><a class="nav-link ${route === '#/lista' ? 'active' : ''}" href="#/lista">Minha lista <span class="list-count">${state.list.length}</span></a></nav><div class="header-actions"><button class="icon-button" data-action="focus-search" aria-label="Buscar">⌕</button><button class="profile-button" data-route="${state.user ? 'perfil' : 'login'}" aria-label="${state.user ? 'Abrir perfil' : 'Entrar'}"><span>${state.user ? state.user.initials : '→'}</span><i></i></button><button class="header-auth-link" data-action="${state.user ? 'logout' : 'login'}">${state.user ? 'Sair' : 'Entrar'}</button></div></header>`;
}

function card(show) {
    const saved = state.list.includes(show.id);
    return `<article class="poster-card dynamic-card"><div class="poster-image" style="background-image:linear-gradient(145deg,rgba(0,0,0,.08),rgba(0,0,0,.3)),url('${show.image}')"><span class="poster-badge">${show.badge || show.genre}</span><button class="card-play" data-action="watch" data-id="${show.id}" aria-label="Assistir ${show.title}">▶</button></div><div class="card-info"><h3><a href="#/serie/${show.id}">${show.title}</a></h3><p>${show.genre} · ${show.episodes} episódios</p><button class="card-more ${saved ? 'saved' : ''}" data-action="toggle-list" data-id="${show.id}" aria-label="${saved ? 'Remover da lista' : 'Adicionar à lista'}">${saved ? '✓' : '＋'}</button></div></article>`;
}

function homePage() {
    const featured = getShow('flor-noite');
    return `<main><section class="hero dynamic-hero" style="--hero-image:url('${featured.image}')"><div class="hero-image"></div><div class="hero-shade"></div><div class="hero-copy"><div class="eyebrow"><span class="eyebrow-line"></span> DramaPlus original · ${featured.year}</div><h1>${featured.title.replace(' ', '<br />')}</h1><p class="hero-description">${featured.description}</p><div class="hero-meta"><span class="rating">★ ${featured.rating}</span><span>${featured.genre}</span><span>${featured.episodes} episódios</span><span>16+</span></div><div class="hero-buttons"><button class="primary-button" data-action="watch" data-id="${featured.id}"><span class="play-icon">▶</span> Assistir agora</button><button class="secondary-button" data-action="toggle-list" data-id="${featured.id}"><span class="plus-icon">＋</span> Minha lista</button></div></div></section><section class="content-section"><div class="section-heading"><div><p class="section-kicker">Escolhidos para você</p><h2>Histórias para sentir <span>sem pressa.</span></h2></div><a href="#/explorar" class="see-all">Ver catálogo <span>→</span></a></div><div class="genre-tabs">${['todos', 'romance', 'comedia', 'misterio', 'historico'].map((filter) => `<button class="genre-tab ${state.filter === filter ? 'active' : ''}" data-filter="${filter}">${filter === 'todos' ? 'Todos' : filter[0].toUpperCase() + filter.slice(1)}</button>`).join('')}</div><div class="poster-row">${filteredShows().slice(0, 5).map(card).join('')}</div></section>${continueSection()}<section class="content-section bottom-section"><div class="section-heading"><div><p class="section-kicker">Para maratonar</p><h2>Mini séries em alta</h2></div><a href="#/explorar" class="see-all">Ver todas <span>→</span></a></div><div class="ranking-row">${shows.slice(6, 9).map((show, index) => `<div class="ranking-item"><span class="ranking-number">0${index + 1}</span><div class="mini-poster" style="background-image:url('${show.image}')"></div><div><h3>${show.title}</h3><p>${show.genre} · ${show.country}</p></div></div>`).join('')}</div></section></main>`;
}

function filteredShows() { return shows.filter((show) => (state.filter === 'todos' || show.key === state.filter) && (!state.query || `${show.title} ${show.genre} ${show.country}`.toLowerCase().includes(state.query.toLowerCase()))); }
function explorePage() { return `<main class="page-shell"><div class="page-heading"><p class="section-kicker">Catálogo DramaPlus</p><h1>Encontre sua próxima<br /><em>história favorita.</em></h1><p>Explore mini-séries selecionadas para cada momento.</p></div><div class="explore-tools"><label class="large-search">⌕<input id="catalog-search" value="${state.query}" placeholder="Buscar por título, país ou gênero..." /></label><div class="genre-tabs">${['todos', 'romance', 'comedia', 'misterio', 'historico', 'drama'].map((filter) => `<button class="genre-tab ${state.filter === filter ? 'active' : ''}" data-filter="${filter}">${filter === 'todos' ? 'Todos' : filter[0].toUpperCase() + filter.slice(1)}</button>`).join('')}</div></div><div class="catalog-grid">${filteredShows().map(card).join('') || '<div class="empty-state"><h2>Nenhum título encontrado</h2><p>Tente buscar por outro termo.</p></div>'}</div></main>`; }
function detailPage(show) { return `<main class="detail-page"><section class="detail-hero" style="--detail-image:url('${show.image}')"><div class="detail-cover"></div><div class="detail-info"><a class="back-link" href="#/explorar">← Voltar ao catálogo</a><p class="section-kicker">${show.genre} · ${show.country}</p><h1>${show.title}</h1><div class="hero-meta"><span class="rating">★ ${show.rating}</span><span>${show.year}</span><span>${show.episodes} episódios</span><span>16+</span></div><p class="detail-description">${show.description} Uma narrativa envolvente sobre encontros improváveis, escolhas e o que acontece quando o coração decide assumir o controle.</p><div class="hero-buttons"><button class="primary-button" data-action="watch" data-id="${show.id}"><span class="play-icon">▶</span> Assistir episódio 1</button><button class="secondary-button" data-action="toggle-list" data-id="${show.id}">${state.list.includes(show.id) ? '✓ Na minha lista' : '＋ Minha lista'}</button></div></div></section><section class="episode-section"><div class="section-heading"><div><p class="section-kicker">Temporada 1</p><h2>Todos os episódios</h2></div><span class="progress-label">${show.episodes} episódios</span></div><div class="episode-list">${Array.from({ length: show.episodes }, (_, index) => `<button class="episode-row" data-action="watch" data-id="${show.id}"><span class="episode-number">${String(index + 1).padStart(2, '0')}</span><span><strong>Episódio ${index + 1}</strong><small>${index === 0 ? 'Comece sua jornada' : 'Legendado em português'} · ${38 + (index % 4)} min</small></span><span class="episode-play">▶</span></button>`).join('')}</div></section></main>`; }
function continueSection() { const show = getShow('primavera'); return `<section class="continue-section"><div class="continue-head"><div><p class="section-kicker">Seu momento</p><h2>Continue de onde parou</h2></div><span class="progress-label">Episódio 05 · 32% concluído</span></div><div class="continue-card"><div class="continue-art" style="background-image:url('${show.image}')"></div><div class="continue-copy"><p class="mini-label">Episódio 05 · 42 min restantes</p><h3>${show.title}</h3><div class="progress-track"><span></span></div><div class="continue-footer"><span>32% concluído</span><button class="text-button" data-action="watch" data-id="${show.id}">Continuar assistindo <span>→</span></button></div></div></div></section>`; }
function listPage() { const saved = shows.filter((show) => state.list.includes(show.id)); return `<main class="page-shell"><div class="page-heading compact"><p class="section-kicker">Sua coleção</p><h1>Minha lista</h1><p>Guarde os títulos que você quer assistir depois.</p></div><div class="catalog-grid">${saved.length ? saved.map(card).join('') : '<div class="empty-state"><h2>Sua lista está vazia</h2><p>Adicione uma série para encontrá-la aqui.</p><a class="primary-button" href="#/explorar">Explorar catálogo</a></div>'}</div></main>`; }
function profilePage() { return `<main class="page-shell profile-page"><div class="profile-header"><div class="profile-avatar">AF</div><div><p class="section-kicker">Seu perfil</p><h1>Olá, Angelina.</h1><p>Você já assistiu a 12 episódios no DramaPlus.</p></div></div><div class="profile-panels"><section><p class="section-kicker">Preferências</p><h2>Como você assiste</h2><label><span>Idioma das legendas</span><select><option>Português (Brasil)</option><option>English</option><option>Español</option></select></label><label><span>Reprodução automática</span><input type="checkbox" checked /></label></section><section><p class="section-kicker">Sua atividade</p><h2>Resumo da conta</h2><div class="stat-line"><strong>${state.list.length}</strong><span>séries na minha lista</span></div><div class="stat-line"><strong>12</strong><span>episódios assistidos</span></div></section></div></main>`; }
function authPage(mode = 'login') { const signup = mode === 'signup'; return `<main class="auth-page"><section class="auth-visual"><a class="brand" href="#/"><span class="brand-mark">D</span><span>Drama<span class="brand-accent">Plus</span></span></a><div><p class="eyebrow"><span class="eyebrow-line"></span> Seu lugar para sentir</p><h1>Histórias que<br /><em>encontram você.</em></h1><p>Descubra mini-séries para todos os momentos, salve seus favoritos e continue assistindo quando quiser.</p></div><span class="auth-quote">“Algumas histórias chegam exatamente quando a gente precisa delas.”</span></section><section class="auth-panel"><div class="auth-card"><a class="auth-back" href="#/">← Voltar ao início</a><p class="section-kicker">DramaPlus</p><h2>${signup ? 'Crie sua conta' : 'Bem-vinda de volta'}</h2><p class="auth-subtitle">${signup ? 'Comece sua próxima maratona hoje.' : 'Entre para continuar suas histórias.'}</p><form id="auth-form" data-mode="${mode}" novalidate>${signup ? '<label>Nome completo<input name="name" type="text" placeholder="Como podemos chamar você?" autocomplete="name" required /></label>' : ''}<label>E-mail<input name="email" type="email" placeholder="voce@email.com" autocomplete="email" required /></label><label>Senha<div class="password-field"><input name="password" type="password" placeholder="Mínimo de 6 caracteres" autocomplete="${signup ? 'new-password' : 'current-password'}" required /><button type="button" data-action="toggle-password" aria-label="Mostrar senha">◉</button></div></label>${signup ? '<label class="check-label"><input name="terms" type="checkbox" required /><span>Concordo com os termos de uso e a política de privacidade.</span></label>' : '<div class="auth-options"><label class="check-label"><input type="checkbox" checked /><span>Lembrar de mim</span></label><a href="#/recuperar">Esqueci minha senha</a></div>'}<p class="auth-feedback" aria-live="polite"></p><button class="primary-button auth-submit" type="submit">${signup ? 'Criar minha conta' : 'Entrar na conta'} <span>→</span></button></form><p class="auth-switch">${signup ? 'Já tem uma conta?' : 'Ainda não tem uma conta?'} <a href="#/${signup ? 'login' : 'criar-conta'}">${signup ? 'Entrar' : 'Criar conta'}</a></p><div class="auth-divider"><span>ou continue com</span></div><div class="social-auth"><button type="button">G</button><button type="button">f</button><button type="button"></button></div></div></section></main>`; }
function recoveryPage() { return `<main class="auth-page"><section class="auth-visual"><a class="brand" href="#/"><span class="brand-mark">D</span><span>Drama<span class="brand-accent">Plus</span></span></a><div><p class="eyebrow"><span class="eyebrow-line"></span> Recuperar acesso</p><h1>Volte para<br /><em>suas histórias.</em></h1><p>Enviaremos um link para você criar uma nova senha e continuar sua maratona.</p></div><span class="auth-quote">“Toda história boa merece um próximo capítulo.”</span></section><section class="auth-panel"><div class="auth-card"><a class="auth-back" href="#/login">← Voltar para entrar</a><p class="section-kicker">DramaPlus</p><h2>Recupere sua senha</h2><p class="auth-subtitle">Informe o e-mail usado na sua conta.</p><form id="recovery-form" novalidate><label>E-mail<input name="email" type="email" placeholder="voce@email.com" autocomplete="email" required /></label><p class="auth-feedback" aria-live="polite"></p><button class="primary-button auth-submit" type="submit">Enviar link <span>→</span></button></form><p class="auth-switch">Lembrou da senha? <a href="#/login">Entrar agora</a></p></div></section></main>`; }
function playerPage(show) { return `<main class="player-page"><div class="player-video"><div class="player-controls"><button data-route="/serie/${show.id}">×</button><span>DramaPlus</span><button aria-label="Configurações">⚙</button></div><video class="video-element" controls poster="${show.image}"><source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4" />Seu navegador não suporta vídeo HTML5.</video><div class="player-center"><button class="video-orb">▶</button><p>Episódio 1 · ${show.title}</p></div></div><div class="player-info"><p class="section-kicker">Episódio 1 de ${show.title}</p><h1>O começo de tudo</h1><p>${show.description}</p><button class="secondary-button" data-route="/serie/${show.id}">Ver detalhes da série</button></div></main>`; }
function notFoundPage() { return `<main class="page-shell empty-page"><p class="section-kicker">DramaPlus</p><h1>Esta página saiu<br /><em>do roteiro.</em></h1><p>O endereço que você acessou não existe.</p><a class="primary-button" href="#/">Voltar para o início</a></main>`; }
function render() { const hash = window.location.hash || '#/'; let view = homePage(); let pageTitle = 'Início'; if (hash === '#/explorar') { view = explorePage(); pageTitle = 'Explorar'; } else if (hash === '#/lista') { view = listPage(); pageTitle = 'Minha lista'; } else if (hash === '#/perfil') { view = profilePage(); pageTitle = 'Perfil'; } else if (hash === '#/login' || hash === '#/entrar') { view = authPage('login'); pageTitle = 'Entrar'; } else if (hash === '#/criar-conta') { view = authPage('signup'); pageTitle = 'Criar conta'; } else if (hash === '#/recuperar') { view = recoveryPage(); pageTitle = 'Recuperar senha'; } else if (hash.startsWith('#/serie/')) { view = detailPage(getShow(hash.split('/')[2]) || shows[0]); pageTitle = getShow(hash.split('/')[2])?.title || 'Série'; } else if (hash.startsWith('#/assistir/')) { view = playerPage(getShow(hash.split('/')[2]) || shows[0]); pageTitle = 'Assistindo'; } else if (hash !== '#/' && hash !== '') { view = notFoundPage(); pageTitle = 'Página não encontrada'; } document.title = `${pageTitle} | DramaPlus`; const isAuth = hash === '#/login' || hash === '#/entrar' || hash === '#/criar-conta' || hash === '#/recuperar'; app.innerHTML = `${isAuth ? '' : header()}${view}${isAuth ? '' : '<footer><a class="brand footer-brand" href="#/"><span class="brand-mark">D</span><span>Drama<span class="brand-accent">Plus</span></span></a><p>Boas histórias encontram você.</p><span class="footer-note">© 2024 DramaPlus</span></footer>'}`; bindEvents(); window.scrollTo(0, 0); }
function bindEvents() { document.querySelectorAll('[data-route]').forEach((element) => element.addEventListener('click', () => go(element.dataset.route === 'perfil' ? '/perfil' : element.dataset.route))); document.querySelectorAll('[data-action="watch"]').forEach((element) => element.addEventListener('click', () => go(`/assistir/${element.dataset.id}`))); document.querySelectorAll('[data-action="toggle-list"]').forEach((element) => element.addEventListener('click', () => { const index = state.list.indexOf(element.dataset.id); if (index === -1) state.list.push(element.dataset.id); else state.list.splice(index, 1); saveState(); render(); })); document.querySelectorAll('[data-filter]').forEach((element) => element.addEventListener('click', () => { state.filter = element.dataset.filter; render(); })); const search = document.querySelector('#catalog-search'); if (search) { search.addEventListener('input', (event) => { state.query = event.target.value; document.querySelector('.catalog-grid').innerHTML = filteredShows().map(card).join('') || '<div class="empty-state"><h2>Nenhum título encontrado</h2><p>Tente buscar por outro termo.</p></div>'; bindEvents(); }); } document.querySelector('[data-action="focus-search"]')?.addEventListener('click', () => go('/explorar')); const authForm = document.querySelector('#auth-form'); authForm?.addEventListener('submit', (event) => { event.preventDefault(); const formData = new FormData(authForm); const feedback = authForm.querySelector('.auth-feedback'); const password = String(formData.get('password') || ''); const mode = authForm.dataset.mode; if (password.length < 6) { feedback.textContent = 'A senha precisa ter pelo menos 6 caracteres.'; feedback.className = 'auth-feedback error'; return; } if (mode === 'signup' && !formData.get('terms')) { feedback.textContent = 'Aceite os termos para continuar.'; feedback.className = 'auth-feedback error'; return; } const name = String(formData.get('name') || 'Angelina Fernandes'); const initials = name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase(); state.user = { name, email: formData.get('email'), initials }; localStorage.setItem('dramaplus-user', JSON.stringify(state.user)); feedback.textContent = mode === 'signup' ? 'Conta criada. Redirecionando...' : 'Login realizado. Redirecionando...'; feedback.className = 'auth-feedback success'; setTimeout(() => go('/'), 650); }); document.querySelector('[data-action="toggle-password"]')?.addEventListener('click', (event) => { const input = event.currentTarget.parentElement.querySelector('input'); input.type = input.type === 'password' ? 'text' : 'password'; }); }
window.addEventListener('hashchange', render);
render();
document.addEventListener('submit', (event) => { if (event.target.id !== 'recovery-form') return; event.preventDefault(); const email = String(new FormData(event.target).get('email') || ''); const feedback = event.target.querySelector('.auth-feedback'); if (!email.includes('@')) { feedback.textContent = 'Digite um e-mail válido.'; feedback.className = 'auth-feedback error'; return; } feedback.textContent = 'Link enviado. Verifique sua caixa de entrada.'; feedback.className = 'auth-feedback success'; });
document.addEventListener('click', (event) => { const action = event.target.closest('[data-action]')?.dataset.action; if (action === 'login') go('/login'); if (action === 'google-login' && !firebaseApi.enabled) { state.user = { name: 'Usuário local', email: 'local@dramaplus.local', initials: 'UL' }; localStorage.setItem('dramaplus-user', JSON.stringify(state.user)); go('/'); } if (action === 'logout' && !firebaseApi.enabled) { localStorage.removeItem('dramaplus-user'); state.user = null; go('/'); } });
function setupGoogleAuth() { const social = document.querySelector('.social-auth'); if (!social || social.dataset.ready) return; social.dataset.ready = 'true'; social.innerHTML = '<button class="google-auth-button" type="button" data-action="google-login"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.35 12.21c0-.72-.06-1.42-.18-2.09H12v3.95h5.24a4.48 4.48 0 0 1-1.94 2.94v2.45h3.14c1.84-1.7 2.91-4.2 2.91-7.25Z"/><path fill="#34A853" d="M12 21.5c2.63 0 4.84-.87 6.45-2.36l-3.14-2.45c-.87.58-1.98.92-3.31.92-2.54 0-4.7-1.72-5.47-4.03H3.28v2.53A9.74 9.74 0 0 0 12 21.5Z"/><path fill="#FBBC05" d="M6.53 13.58A5.85 5.85 0 0 1 6.22 12c0-.55.1-1.09.31-1.58V7.89H3.28A9.74 9.74 0 0 0 2.25 12c0 1.57.38 3.05 1.03 4.11l3.25-2.53Z"/><path fill="#EA4335" d="M12 6.39c1.44 0 2.73.5 3.75 1.49l2.81-2.81C16.84 3.48 14.63 2.5 12 2.5a9.74 9.74 0 0 0-8.72 5.39l3.25 2.53C7.3 8.11 9.46 6.39 12 6.39Z"/></svg><span>Continuar com Google</span></button>'; }
const authObserver = new MutationObserver(setupGoogleAuth);
authObserver.observe(app, { childList: true, subtree: true });
setupGoogleAuth();
firebaseApi.observeAuth(async (user) => { state.user = user; if (user) { localStorage.setItem('dramaplus-user', JSON.stringify(user)); const cloudList = await firebaseApi.loadList(user.uid).catch(() => null); if (cloudList) { state.list = cloudList; localStorage.setItem('dramaplus-list', JSON.stringify(state.list)); } } else if (firebaseApi.enabled) { state.user = null; localStorage.removeItem('dramaplus-user'); } render(); });
document.addEventListener('submit', async (event) => { if (!firebaseApi.enabled || event.target.id !== 'auth-form') return; event.preventDefault(); event.stopImmediatePropagation(); const form = event.target; const data = new FormData(form); const mode = form.dataset.mode; const feedback = form.querySelector('.auth-feedback'); try { const user = mode === 'signup' ? await firebaseApi.signup(String(data.get('name') || ''), String(data.get('email') || ''), String(data.get('password') || '')) : await firebaseApi.login(String(data.get('email') || ''), String(data.get('password') || '')); state.user = user; localStorage.setItem('dramaplus-user', JSON.stringify(user)); feedback.textContent = 'Acesso confirmado. Redirecionando...'; feedback.className = 'auth-feedback success'; setTimeout(() => go('/'), 650); } catch (error) { feedback.textContent = error.code === 'auth/invalid-credential' ? 'E-mail ou senha inválidos.' : 'Não foi possível concluir agora. Verifique os dados.'; feedback.className = 'auth-feedback error'; } }, true);
document.addEventListener('click', async (event) => { if (!firebaseApi.enabled) return; const action = event.target.closest('[data-action]')?.dataset.action; if (action !== 'google-login' && action !== 'logout') return; event.preventDefault(); event.stopImmediatePropagation(); const button = event.target.closest('[data-action]'); try { if (action === 'google-login') { button.disabled = true; button.classList.add('is-loading'); const user = await firebaseApi.googleLogin(); if (user) { state.user = user; localStorage.setItem('dramaplus-user', JSON.stringify(user)); go('/'); } } else { await firebaseApi.logout(); state.user = null; localStorage.removeItem('dramaplus-user'); go('/'); } } catch (error) { console.error('Firebase auth error', error); const feedback = document.querySelector('.auth-feedback'); if (feedback) { const messages = { 'auth/unauthorized-domain': 'Este domínio não está autorizado no Firebase.', 'auth/operation-not-allowed': 'Ative o login com Google no Firebase Authentication.', 'auth/popup-blocked': 'O popup foi bloqueado. Permita popups para continuar.', 'auth/popup-closed-by-user': 'A janela do Google foi fechada antes do login.', 'auth/invalid-api-key': 'A chave do Firebase está inválida.' }; feedback.textContent = messages[error.code] || `Não foi possível entrar com o Google agora (${error.code || 'erro desconhecido'}).`; feedback.className = 'auth-feedback error'; if (button) { button.disabled = false; button.classList.remove('is-loading'); } } } }, true);
